on:
  push:
    branches:
      - main
name: Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Storage Permission
        run: chmod -R 777 storage bootstrap/cache
      - name: Freshing database
        run: php artisan migrate
      - name: Run Testsuite
        run: php artisan test
      - name: Get latest code
        uses: actions/checkout@v2.3.2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 77.222.40.224
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/


